name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    First_Job:
        name: Testing
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo " hello from github actions"

        - name: list the files
          run: ls

        - name: read the files
          run: cat README.md

       
